### ISSUE TITLE
Exploring alternative octree traversal options

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Voxel-demo#73]
We might want to explore alternative ways of traversing our octree.

This is not suggested as a replacement for what we are doing now, but as an enhancement.

The problems for optimal route to random access and selecting a region, for example are quite different and if random access methods are used for selecting a region it would be inefficient.

Think of a situation where you have an arbitrary number of chunks you want to select that are in the same region. Would you traverse the octree N times from top to bottom to select all the chunks? No. You would rather want to use the dimensions of the group of octants which contain the chunks to select the closest matching octant which contains all the rest of the octants - and ultimately chunks.

How to do something like that? Once the dimensions are known one traversal method would be returning back as much as is needed and iterating forward from there.

Another one might be using bottom to top approach for some tasks.

This ticket is here to remind that we want to explore additional octree traversal methods for different use cases.

1) Map out common use cases we are likely to encounter.
2) Research.
3) Suggest.
4) Implement.

**Comment by Pawlost** [comment]
Only reason why to traverse octrees is to get leaft nodes in surrounding area, if we then have them we can use this https://github.com/starandserpent/Foreman/issues/6 to access those leaf nodes without traversing octree. I think the point is not explore alternative octree traversal but how to traverse it less. Since issue 6 (meantioned above) is providing it I am closing this issue.
