### ISSUE TITLE
Research making one solid mesh with multiple textures

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Voxel-demo#98]
Research making one solid mesh with multiple textures. Currently we don't know how to do it.

**Comment by Pawlost** [comment]
This probably requires using own Material. We are currently using default godot Spatial Material which contains default shader. Although I think this is unnecesary due to this if this https://github.com/starandserpent/Terra/issues/4 could be  implemented and because we are using Visual server to bypass godot result would be same.

**Comment by Pawlost** [comment]
This truly seems like uneccesary I will close it for now and reopen if needed.
