### ISSUE TITLE
Look into backface culling

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Voxel-demo#99]
It seems we currently have faces on both sides, even when it's not necessary.

**Comment by Pawlost** [comment]
No we dont. This issue is related to this https://github.com/starandserpent/Terra/issues/4. 

![unknown](https://user-images.githubusercontent.com/32877330/83386955-32510000-a3ec-11ea-94ed-c8d08f4c33d5.png)

This is more of a bug or bad decision which I made and which I explain in issue 4 linked above. To prove this as you can see in the image if backface culling wasnt enabled the inner faces would look like **1** but instead in **3** there you can clearly see through textures. This is combination of chunk border and rendered mesh of another material (issue 4). I will link issue explaining chunk borders later.

**Comment by Pawlost** [comment]
https://github.com/starandserpent/Terra/issues/5

**Comment by Pawlost** [comment]
Done

**Comment by Pawlost** [comment]
Culling between chunks already opened here. https://github.com/starandserpent/Voxel-demo/issues/33
